projects:
  Codegen Project:
    schemaPath: schema.graphql
    includes:
      - graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: graphql/API.ts
        docsFilePath: graphql
        region: us-east-1
        apiId: gf3v2kpn6vgkddufvlqxli7ff4
        frontend: javascript
        framework: react
        maxDepth: 8
extensions:
  amplify:
    version: 3
