import Head from 'next/head'
import type { NextPage } from 'next'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import { Auth } from 'aws-amplify'
import { Button } from '@nextui-org/react';

const Home: NextPage = () => {
  const [response, setResponse] = useState<any>({})

  const login = async () => {
    try {
      const username = 'cristian.agency'
      const password = 'Temporal01'
      const responseData = await Auth.signIn(username, password)
      setResponse(responseData)
    } catch (error) {
      console.log('error', error)
      alert('Se presento un error' + error);
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <Button onClick={login}> Login</Button>
        <div>
          {
            response && (
              <pre>
                <code>
                  {JSON.stringify(response, null, 2)}
                </code>
              </pre>
            )
          }
        </div>
      </main>

    </div>
  )
}

export default Home
