// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

export const awsExports = {
  aws_appsync_graphqlEndpoint: "https://qsnx66v2qvbmvatmdpqnm5qyay.appsync-api.us-east-1.amazonaws.com/graphql",
  aws_appsync_region: "us-east-1",
  aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
  aws_appsync_apiKey: "da2-iolspbnmyvg6pdzrb4334c3mzi",
}