import Head from 'next/head'
import type { NextPage } from 'next'
import { Card, Container, Divider, Grid, Text } from '@nextui-org/react'
import { FormProject } from '@modules/project/components'

const Project: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Card>
        <Card.Header>
          <Grid.Container gap={4}>
            <Grid>
              <Text h2>New project</Text>
            </Grid>
          </Grid.Container>
        </Card.Header>
        <Divider />
        <Card.Body css={{ py: '$15' }}>
          <FormProject />
        </Card.Body>
      </Card>
    </>
  )
}

export default Project
