import Head from 'next/head'
import type { NextPage } from 'next'
import { Button, Row, Text } from '@nextui-org/react'
import { BsPlus } from 'react-icons/bs'
import Link from 'next/link'

const Project: NextPage = () => {
  return (
    <>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Row justify="space-between">
        <Text h2 weight="bold">
          Projects 1
        </Text>

        <Link href="/projects/create">
          <Button auto icon={<BsPlus size={40} />}></Button>
        </Link>
      </Row>
    </>
  )
}

export default Project
