import Head from 'next/head'
import type { NextPage } from 'next'
import { Button, Card, Row, Spacer, Text } from '@nextui-org/react'
import { BsPlus } from 'react-icons/bs'
import Link from 'next/link'
import store, { AppStore } from '@/redux/store'
import { useEffect } from 'react'
import { projectService } from '@/modules/project/services'
import { useDispatch, useSelector } from 'react-redux'
import { loadProjects } from '@/redux/slices'
import { CardProject } from '@/modules/project/components'

const Project: NextPage = () => {
  const projects = useSelector((state: AppStore) => state.project.list)
  const dispatch = useDispatch()

  useEffect(() => {
    ;(async () => {
      const response = await projectService.getAll()

      dispatch(loadProjects(response))
    })()
  }, [])

  return (
    <>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Row justify="space-between">
        <Text h2 weight="bold">
          Projects 1
        </Text>

        <Link href="/projects/create">
          <Button auto icon={<BsPlus size={40} />}></Button>
        </Link>
      </Row>
      <Spacer y={3} />
      <Card>
        {projects.map((project) => (
          <CardProject key={project.id} {...project} />
        ))}
      </Card>
    </>
  )
}

export default Project
